"""Generate the spoken prompts baked into the firmware (../prompts.h, ../prompts.cpp),
plus .wav copies in previews/ to listen to.

Run once, and again whenever you change a phrase:
    python3 esp32/kcsm_audiokit/tools/make_prompts.py

Needs OPENAI_API_KEY in the environment and ffmpeg on the PATH. The clips are
stored as 16 kHz mono mu-law (8 KB per second of speech).
"""

import json
import os
import subprocess
import urllib.request
from pathlib import Path

VOICE = "nova"
MODEL = "gpt-4o-mini-tts"
INSTRUCTIONS = (
    "You are the voice of a small home radio. Speak clearly, warmly and at a "
    "relaxed pace. Pronounce KCSM as the letters K C S M."
)
SAMPLE_RATE = 16000

# id -> phrase. The firmware strings some of these together (e.g. BT_A + TO_PAIR).
PROMPTS = {
    "BT_A": "Bluetooth A.",
    "BT_B": "Bluetooth B.",
    "TO_PAIR": "To pair, choose KCSM Radio in your device's Bluetooth settings.",
    "RECONNECTING": "Reconnecting to your device.",
    "PAIR_NEW": "To pair a new device, choose KCSM Radio in its Bluetooth settings.",
    "DEVICE_A_CONNECTED": "Device A connected.",
    "DEVICE_B_CONNECTED": "Device B connected.",
    "BACK_TO_RADIO": "Back to radio.",
    "FORGOTTEN": "All devices forgotten.",
    "NO_WIFI": "Can't connect to WiFi. Retrying.",
}

OUT_DIR = Path(__file__).resolve().parent.parent
PREVIEW_DIR = Path(__file__).resolve().parent / "previews"  # .wav copies to listen to


def tts(text: str) -> bytes:
    """Returns 24 kHz 16-bit mono PCM."""
    req = urllib.request.Request(
        "https://api.openai.com/v1/audio/speech",
        data=json.dumps({
            "model": MODEL,
            "voice": VOICE,
            "input": text,
            "instructions": INSTRUCTIONS,
            "response_format": "pcm",
        }).encode(),
        headers={
            "Authorization": f"Bearer {os.environ['OPENAI_API_KEY']}",
            "Content-Type": "application/json",
        },
    )
    with urllib.request.urlopen(req) as resp:
        return resp.read()


def to_mulaw(pcm24k: bytes) -> bytes:
    """Trims leading/trailing silence, normalizes loudness, resamples to 16 kHz mu-law."""
    trim = "silenceremove=start_periods=1:start_threshold=-45dB"
    return subprocess.run(
        ["ffmpeg", "-loglevel", "error",
         "-f", "s16le", "-ar", "24000", "-ac", "1", "-i", "pipe:0",
         "-af", f"{trim},areverse,{trim},areverse,loudnorm=I=-16:TP=-1.5",
         "-ar", str(SAMPLE_RATE), "-ac", "1", "-f", "mulaw", "pipe:1"],
        input=pcm24k, capture_output=True, check=True,
    ).stdout


def write_preview(name: str, clip: bytes):
    """Saves the exact firmware audio as a .wav so it can be checked by ear."""
    subprocess.run(
        ["ffmpeg", "-loglevel", "error", "-y",
         "-f", "mulaw", "-ar", str(SAMPLE_RATE), "-ac", "1", "-i", "pipe:0",
         str(PREVIEW_DIR / f"{name}.wav")],
        input=clip, check=True,
    )


def main():
    PREVIEW_DIR.mkdir(exist_ok=True)
    names = [f"PROMPT_{name}" for name in PROMPTS]
    header = [
        "// Generated by tools/make_prompts.py. Do not edit by hand.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define PROMPT_SAMPLE_RATE {SAMPLE_RATE}",
        "",
        "struct Prompt { const uint8_t* data; uint32_t len; };",
        "",
        "enum PromptId {",
        *[f"  {n},  // \"{text}\"" for n, text in zip(names, PROMPTS.values())],
        "  PROMPT_COUNT",
        "};",
        "",
        "extern const Prompt PROMPTS[PROMPT_COUNT];",
        "",
    ]
    source = [
        "// Generated by tools/make_prompts.py. Do not edit by hand.",
        f"// {SAMPLE_RATE} Hz mono mu-law, OpenAI TTS voice \"{VOICE}\".",
        '#include "prompts.h"',
        "",
    ]
    total = 0
    for name, text in PROMPTS.items():
        clip = to_mulaw(tts(text))
        total += len(clip)
        write_preview(name, clip)
        print(f"{name:20s} {len(clip) / SAMPLE_RATE:4.1f}s  {text}")
        hexbytes = ",".join(f"0x{b:02x}" for b in clip)
        source.append(f"static const uint8_t {name}[] = {{{hexbytes}}};")
    source += ["", "const Prompt PROMPTS[PROMPT_COUNT] = {"]
    source += [f"  {{{name}, sizeof({name})}}," for name in PROMPTS]
    source += ["};", ""]
    (OUT_DIR / "prompts.h").write_text("\n".join(header))
    (OUT_DIR / "prompts.cpp").write_text("\n".join(source))
    print(f"Wrote prompts.h and prompts.cpp ({total / 1024:.0f} KB of audio)")


if __name__ == "__main__":
    main()
