// Generated by tools/make_prompts.py. Do not edit by hand.
#pragma once
#include <stdint.h>

#define PROMPT_SAMPLE_RATE 16000

struct Prompt { const uint8_t* data; uint32_t len; };

enum PromptId {
  PROMPT_BT_A,  // "Bluetooth A."
  PROMPT_BT_B,  // "Bluetooth B."
  PROMPT_TO_PAIR,  // "To pair, choose KCSM Radio in your device's Bluetooth settings."
  PROMPT_RECONNECTING,  // "Reconnecting to your device."
  PROMPT_PAIR_NEW,  // "To pair a new device, choose KCSM Radio in its Bluetooth settings."
  PROMPT_DEVICE_A_CONNECTED,  // "Device A connected."
  PROMPT_DEVICE_B_CONNECTED,  // "Device B connected."
  PROMPT_BACK_TO_RADIO,  // "Back to radio."
  PROMPT_FORGOTTEN,  // "All devices forgotten."
  PROMPT_NO_WIFI,  // "Can't connect to WiFi. Retrying."
  PROMPT_COUNT
};

extern const Prompt PROMPTS[PROMPT_COUNT];
